project_root: D:/study/02_science_product/underwater_enhancement

raw_images: D:/study/02_science_product/underwater_enhancement/data/raw/images

baseline_outputs: D:/study/02_science_product/underwater_enhancement/outputs/baselines
wb_outputs: D:/study/02_science_product/underwater_enhancement/outputs/baselines/white_balance
cc_outputs: D:/study/02_science_product/underwater_enhancement/outputs/baselines/color_compensation
clahe_outputs: D:/study/02_science_product/underwater_enhancement/outputs/baselines/clahe
retinex_outputs: D:/study/02_science_product/underwater_enhancement/outputs/baselines/retinex
